name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3


    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.1.app


    - name: Build and test
      run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

  build-and-test-ios:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3


    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.1.app


    - name: Build and test
      run: xcodebuild clean build test -workspace EssentialApp/EssentialApp.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform:iOS Simulator, id:17EAD5F6-22A4-4C78-BFDF-2E93523F7A21, OS:16.1, name:iPhone 14" ONLY_ACTIVE_ARCH=YES
